# Generated by Django 3.2.4 on 2021-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('parrot', 'parrot')], max_length=6),
        ),
    ]
