# Generated by Django 3.2.5 on 2021-07-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
    ]
