# Generated by Django 3.2.4 on 2021-06-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='name',
        ),
    ]
