# Generated by Django 3.2.4 on 2021-06-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_rename_state_todo_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state_id',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='todo',
            name='person_test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
