# Generated by Django 3.2.4 on 2021-06-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20210617_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='name_of_task',
        ),
    ]
