# Generated by Django 3.2.4 on 2021-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
    ]
